### PR TITLE
Default implementation of `translations` method

### PR DESCRIPTION
**Pull request by alepeino**
In the spirit of keeping the package as simple to use and configure as possible, I added this functionality which allows several ways to configure the `translations` relation, including the default one, pure convention over configuration. (This uses anonymous classes thus avoiding the need to define a separate model -- and covers 95% of my use cases, which is what inspired me to do this change).

Take a look at the updated README (I simplified it a bit) for more details.

All configuration options are tested with the same tests, abstracted into a trait.

### CODE REVIEW

**Comment by alepeino** [comment]
Closing it for now because I just found a problem when defining using multiple default anonymous classes. Will open again when it is solved

**Comment by vinkla** [comment]
Thanks for the pull request. I'll look at any pull request you send my way.

**Comment by alepeino** [comment]
@vinkla great. This was a heavy one. But sadly I found it can fail when more than one "default" translations class is used at the same time.
I'm looking for alternatives but it doesn't seem possible. Are you interested in providing this?

**Comment by vinkla** [comment]
Too bad it can't be done. I'm interested in any optimization.

**Pull request closed without merging**
