### PR TITLE
Support eager loading translations

### PR DESCRIPTION
**Pull request by alepeino**
Revisiting PR #34, whose feature must have been left behind in a version change.

Additionally to caching the translations, this PR loads the translation as an Eloquent relation. Also, I added a query scope for easily eager loading translations for a single locale.

### CODE REVIEW

**Comment by alepeino** [comment]
@vinkla I see the travis tests fail for this one. It's the testbench dependency #70 was aimed at. It will pass if you merge this after the other one. (I tried to keep both PRs separate, but there's this conflict here...)

**Comment by vinkla** [comment]
Okay, lets merge #70 first then we can rebase and merge this in.

**Comment by alepeino** [comment]
(Ok, ended up opening another one: #72 )

**Comment by vinkla** [comment]
Closing in favour of #72.

**Pull request closed without merging**
