### PR TITLE
Add save, update and fill methods to the trait

### PR DESCRIPTION
**Pull request by vinkla**
Closes #5

### CODE REVIEW

**Comment by alexleonard** [comment]
@vinkla Is there any chance you could provide some documentation on the way to approach creating/updating multi lingual data?

I'm envisioning a form on the backend with two text areas, one for each language in the site I'm building, but I'm not sure how I'd go about saving that data to the associated records on the model_translations table.

Thanks!

**Comment by vinkla** [comment]
@alexleonard I could definitely try to add better documentation.

With this package you can currently only update one language at the time. It uses the language you've set in your application `App::setLocale('en')`.

Creating a new instance of an Eloquent object will automatically create a instance of the translation Eloquent object with the translated attributes in your `$translatableAttributes`.

```php
$article = Article::create([
  'title' => 'My Title',
  'content' => 'Great content about weird stuff.',
  'thumbnail' => 'awesome-picture.jpg'
]);
```

In the example above the `title` and `content` attributes are translatable and will be saved in the `article_translations` table with the current locale `locale_id`.

I hope this makes it a bit clearer, please let me know if you want to a more detailed version.

**Comment by alexleonard** [comment]
@vinkla Thanks for the clarification. So I just need to save the article with say the English input first, and then change the locale, save it again with the other language's input, switch my locale back, and return back.

I'll test it out :) Thanks :+1:

**Comment by vinkla** [comment]
@alexleonard That is correct. I usually share a `$locales` property among all views to easily change between them with a `<select>` list in the applications administrator dashboard. 

```php
View::share('locales', $locales);
View::share('currentLocale', Session::get('locale'));
```

Great! Let me know if I can help out more.

**Comment by vinkla** [comment]
@alexleonard I've added an example application to the README. Check it out! https://github.com/vinkla/translator#example

**Pull request merged**
